language: php
php:
  # - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable
    - RELEASE=dev

before_install:
  # - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php5dismod xdebug
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install
  - apt-get update
  - apt-get install phantomjs
  - npm install -g pa11y
  - npm install forever -g

script:
  - printf "127.0.0.1 example.mcdev" >> /etc/hosts
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.0.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd ./web
  - ./../bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../bin/drush
  - ./../bin/drupal
  # Drupal coding standards test on custom modules
  - ./../tests/code-sniffer.sh ./web
  # Drupal accessibiity tests
  - ./../tests/pa11y/pa11y-review.sh http://127.0.0.1:8080
  # Drupal behat tests
  - ./../tests/behat/behat-run.sh http://127.0.0.1:8080
